### ISSUE TITLE
Crossbrowsing

### ISSUE THREAD

**Issue by softwat** [HangHae99Zzz/dream_escape-fe#74]
2022.3.29~4.5
테스터로 사용 할 브라우저를 코멘트에 남겨주세요!

**Comment by softwat** [comment]
사파리, 크롬, 파이어폭스

**Comment by softwat** [comment]
safari 15.0 부터 webRTC가 작동하지 않음 따라서 사파리 클라이언트에게 다른 브라우저를 쓰도록 안내 합니다
https://developer.apple.com/forums/thread/689293

**Comment by hyemin9403** [comment]
Safari 특정 OS(BigSur), 특정 버전(safari 15.0)에서만 발생하는 이슈가 아닌지 확인 필요

**Comment by softwat** [comment]
BigSur에서 발생하는 이슈로 판명.
